# Generated by Django 6.1.1 on 2026-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
    ]
