# Generated by Django 6.1.1 on 2026-09-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='Only authorized users can login'),
        ),
    ]
