# Generated by Django 6.1.1 on 2026-09-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_approved_at_employee_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_data',
            field=models.TextField(blank=True, help_text='JSON encoded face descriptors for face lock'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_registered',
            field=models.BooleanField(default=False, help_text='Whether face is registered for face lock'),
        ),
    ]
