# Generated by Django 6.1.1 on 2026-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_reports_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('picture_b64', models.TextField(help_text='Base64 encoded background image (data URI)')),
                ('picture_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login background',
                'verbose_name_plural': 'Login backgrounds',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
