# Generated by Django 6.1.1 on 2026-09-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('working_days_per_month', models.IntegerField(default=30, help_text='Total working days in a month')),
                ('absent_deduction_per_day', models.DecimalField(decimal_places=2, default=100.0, help_text='Fixed deduction per absent day (leave 0 to use per-day salary)', max_digits=5)),
                ('use_per_day_salary_for_absent', models.BooleanField(default=True, help_text='If checked, absent deduction = daily salary. If unchecked, uses fixed amount above')),
                ('half_day_deduction_percent', models.IntegerField(default=50, help_text='Percentage of daily salary deducted for half day (0-100)')),
                ('late_allowed_per_month', models.IntegerField(default=3, help_text='Number of late arrivals allowed per month without deduction')),
                ('late_deduction_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed deduction per late beyond allowed limit', max_digits=10)),
                ('approved_leave_paid', models.BooleanField(default=True, help_text='Are approved leaves fully paid?')),
                ('tax_rate_percent', models.IntegerField(default=10, help_text='Tax percentage on gross salary')),
                ('performance_bonus_enabled', models.BooleanField(default=True, help_text='Enable attendance-based performance bonus')),
                ('bonus_100_percent', models.IntegerField(default=10, help_text='Bonus % for 100% attendance')),
                ('bonus_95_percent', models.IntegerField(default=5, help_text='Bonus % for 95-99% attendance')),
                ('bonus_90_percent', models.IntegerField(default=2, help_text='Bonus % for 90-94% attendance')),
                ('bonus_below_90_percent', models.IntegerField(default=0, help_text='Bonus % for below 90% attendance')),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Monthly medical allowance', max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Monthly transport allowance', max_digits=10)),
                ('house_allowance_percent', models.IntegerField(default=0, help_text='House rent allowance as % of basic salary')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='generated_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto Generated')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='PayrollBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_days', models.IntegerField(default=30)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_half_day', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('days_holiday', models.IntegerField(default=0)),
                ('days_approved_leave', models.IntegerField(default=0)),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_earned', models.DecimalField(decimal_places=2, default=0, help_text='Salary earned based on attendance', max_digits=10)),
                ('attendance_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Deduction for absent/half-day', max_digits=10)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Deduction for late arrivals', max_digits=10)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Bonus based on attendance %', max_digits=10)),
                ('bonus_percentage', models.IntegerField(default=0, help_text='Bonus percentage applied')),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allowances_computed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_computed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='payroll.payroll')),
            ],
            options={
                'verbose_name_plural': 'Payroll Breakdowns',
            },
        ),
    ]
