# Generated by Django 6.1.1 on 2026-09-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0003_boutiqueitem_budgetloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoutiqueIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('is_deducted', models.BooleanField(default=False)),
                ('issued_by', models.CharField(blank=True, help_text='Boutique manager name', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deducted_in_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutique_deductions', to='payroll.payroll')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique_issues', to='employees.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='payroll.boutiqueproduct')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.DeleteModel(
            name='BoutiqueItem',
        ),
    ]
